### ISSUE TITLE
WARNING:asyncio:socket.send() raised exception.

### ISSUE THREAD

**Issue by StarrySai** [Jc2k/hpfeeds3#8] opened 2019-11-25 00:55 UTC
please help me.
Every time I run it for a day or so, hpfeeds[broker] will report an error:

```
WARNING:asyncio:socket.send() raised exception.
```

I have to restart hpfeeds[broker]，then it works.

How can I solve this problem?

**Comment by Jc2k** [comment] 2019-11-25 10:29
Are you running with TLS enabled by any chance? There are some warnings printed deep inside the python standard library that we can't catch. Other than cluttering up the log files these haven't caused any problems for me, and afaict they are when a connection has closed (at L3, not an application/protocol thing). The client should normally reconnect and carry on. Are you seeing otherwise?

**Comment by StarrySai** [comment] 2019-11-27 09:53
> Are you running with TLS enabled by any chance? There are some warnings printed deep inside the python standard library that we can't catch. Other than cluttering up the log files these haven't caused any problems for me, and afaict they are when a connection has closed (at L3, not an application/protocol thing). The client should normally reconnect and carry on. Are you seeing otherwise?

I did not enable TLS.
When the warning occurs, the hpfeeds client shows that it cannot connect successfully.
Right now, I'm not using asynchronous, it works fine for more than 1 day.
client asynchronous:
`from hpfeeds.asyncio import ClientSession
hps =ClientSession(ip, port, ident, secret)
hps.publish(chan,item)`
client synchronous:
`import hpfeeds
hps =hpfeeds.new(ip,port,ident,secret)
hps.publish(chan,item)`

Although I don't know why, thank you very much for your reply!

**Comment by qboy0000** [comment] 2019-12-04 05:56
i have the same problem. every time  i restart the hpfeedsbroker. sometimes i want to switch back hpfeed2。

**Comment by StarrySai** [comment] 2019-12-09 01:08
This issue happened again, although restarting hpfeeds3-broker resolved the issue. 
error：
`WARNING:asyncio:socket.send() raised exception.`
Is there an effective way？I just want to use hpfeeds3.

**Comment by Jc2k** [comment] 2019-12-09 07:07
I'm not really sure what the problem is - i had the broker running with hundreds of clients and it (the broker) never hung. This is both with and without TLS and with local clients and remote clients. I used python sync and async clients. I used perl clients.

I did see the error you are reporting but it was always a non fatal one. Everything I could find on it was that it was a low level internal asyncio warning because a remote connection had abruptly ended. When you do an asynchronous write it is queued, and so when such a write fails there isn't anywhere for an exception to go, so it just logs it. 

I need as much information as possible to have a chance at recreating this.

 * What OS version
 * What python version
 * Are you using custom clients or existing honeypots
 * How "far" away are the clients from the broker?
 * How large is the data you are sending
 * How many events are you sending
 * How many clients?
 * Is it a single client that gets stuck, or can other clients still connect? If there are other connected clients do they get stuck as well?
 * Have you tried stracing the client or server when its stuck?
 * What's memory usage like during this time?
 * What is the channel name you are using?
 * Whats memory and cpu usage like during this?
 * How is it all deployed?

Ideally a git repo where i can just run `docker-compose up` and after some time i would see the error would be ideal.

The only major issue we have had with hpfeeds was a bug in the old hpfeeds gevent version that meant that concurrent writes could get interleaved. So if 2 clients wrote to it at the same time and the payloads were over a certain size the protocol stream would get corrupted and clients would read a size header that said 1GB and start reading the next 1GB into memory as a single event. The new version tries to stop that from happpening. Asyncio isn't prone to interleaving issues but also the parser is much stricter.

If the broker has actually hung then either - it's in a busy loop and there should be high CPU usage, its completely stopped listening (so the port wont show as open in `netstat`) or it will be blocked on a syscall somewhere (find out with strace).

And if its totally hung the monitoring should break. Even if you aren't using prometheus it would be good for you to turn the exporter port on (`'--exporter=0.0.0.0:9431'`) and `curl http://127.0.0.1/metrics` when the broker has hung. Does it reply? Are the values changing?

Have you captured any other information that might be useful when this happens?

**Comment by StarrySai** [comment] 2020-03-23 03:45
supervisor ERROR：
```
ERROR:pyhpfeeds:Could not connect to broker 127.0.0.1[127.0.0.1]
Traceback (most recent call last):
  File "/home/xxx_env/lib/python3.7/site-packages/hpfeeds/client.py", line 123, in connect
    self.s.connect((addr, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
WARNING:pyhpfeeds:FeedException while connecting
Traceback (most recent call last):
  File "/home/xxx_env/lib/python3.7/site-packages/hpfeeds/client.py", line 88, in tryconnect
    return self.connect()
  File "/home/xxx_env/lib/python3.7/site-packages/hpfeeds/client.py", line 136, in connect
    'Could not connect to broker {}'.format(self.host)
hpfeeds.exceptions.FeedException: Could not connect to broker 127.0.0.1
connected to hpfeeds
WARNING:pyhpfeeds:recv() returned empty string
```

broker ERROR:
`WARNING:asyncio:socket.send() raised exception.`


try:
`curl http://127.0.0.1:9431/metrics`
It doesn't reply to me


Finally I restart broker, it works.
curl http://127.0.0.1:9431/metrics , it replys me.

I'm confused.

**Comment by prashantvidja** [comment] 2020-03-28 11:54
Hello @Jc2k 
the same issue getting below logs continuously.
I have check CPU it's almost full and also completely stopped listening.
check below systemd log.
![WhatsApp Image 2020-03-28 at 5 18 45 PM](https://user-images.githubusercontent.com/26060662/77822452-eac2a500-7118-11ea-9d37-92171af50f63.jpeg)

**Comment by prashantvidja** [comment] 2020-03-28 12:35
What OS version 

> Ubuntu 16.04.6 LTS


What python version

> python 3.6.3


Are you using custom clients or existing honeypots

> Yes, I have created custom client.


How "far" away are the clients from the broker?

> clients are too far from broker. installed in different countries. 


How large is the data you are sending

> receiving only 1 small string.


How many events are you sending

> sending events at every 5 seconds.


How many clients?

> around 40


Is it a single client that gets stuck, or can other clients still connect? If there are other connected clients do they get stuck as well?

> all clients getting stuck due to broker hung.


Have you tried stracing the client or server when its stuck?

> Yes, not receiving any events.


What's memory usage like during this time?

> memory usage normal.


What is the channel name you are using?

> status.events


Whats memory and cpu usage like during this?

> memory usage ~480 mb CPU usage 100%


How is it all deployed?

> I have deployed hpfeed-broker after creating virtualenv installed using pip. also I am using mongo database locally.
> and for client i have run script using threading which send event at every 5 second.

**Comment by prashantvidja** [comment] 2020-04-01 05:12
> i have the same problem. every time i restart the hpfeedsbroker. sometimes i want to switch back hpfeed2。

Does it solve the issue?

**Comment by Jc2k** [comment] 2020-04-01 05:58
Hpfeeds2 doesn’t work on python 3. It also corrupts the subscriber stream and hangs if you have a busy honeypot like cowrie. Also if your input rate is faster than your output there is no mitigation and the buffers grow until you run out of memory. And for low traffic stuff it might just stall. Real problems like this are why hpfeeds 3 exists. But sure, it might not have this particular problem.

I’m sorry I haven’t been able to debug your problem remotely like I was able to debug my own problems with hofeeds 2. It’s really hard to debug something you can’t see or touch. And in my environments (which are similar but larger) I’ve not experienced it.

What debugging have you tried on your own? Have you tried strace? What’s the memory usage and cpu usage like when it happens? Can you share the code for the client? Have you tried running tcpdump and seeing it a particular message from the publisher is causing it? Can you recreate it with less honeypots? What’s your event throughout? Events per second and bytes per second? Have you tried setting up Prometheus monitoring?

Also note that hpfeeds3 itself is deprecated. The changes were merged upstream. I will try to help you here as the context is here but make sure you are using github.com/hpfeeds/hpfeeds.

**Comment by Jc2k** [comment] 2020-04-01 06:01
Sorry for dupe info requests btw, replying in the new GH app and hard to refer back to existing messages while typing!

Be more specific about strace. Is there no output at all? That indicates it’s hung in user space. CN you paste what you see.

Is that memory usage high for the server it’s on? Is it growing or does it stay there.

**Comment by Jc2k** [comment] 2020-04-01 06:02
How long does it take to break?

**Comment by prashantvidja** [comment] 2020-04-01 07:44
Hello @Jc2k 
Thanks for the replay,
I am not getting these exceptions continuously. this working fine for 4-5 days after that instantly I was seeing CPU rises to 100% and service throwing exception continuously. but the memory remains normal.
> What debugging have you tried on your own?

I have checked `htop` for memory and CPU usage. and also I have checked `journalctl -f` for check journal logs because I have started the hpfeeds-broker using the systems.
> Have you tried strace?

I have not tried strace. Hpfeeds-broker stopped so I did not get too much time to strace it. Immediately I have restarted the service. Next time I will check it all things.
> Can you share the code for the client? 

Please check the little function which I have used in client.
```python
import hpfeeds
import threading

def SendStatus():
    client = hpfeeds.new('Hostname', 'port', 'ident', 'secret')
    client.publish('status.events', 'small_payload')
    client.close()
    threading.Timer(5, SendStatus).start()

SendStatus()
```
>Have you tried running tcpdump and seeing it a particular message from the publisher is causing it?

No, I have not tried the tcpdump but I have tried `tcpflow -i eth0 -c port 10000` but before I do this command it is stopped listening, so did not find out any publish events.

> Can you recreate it with less honeypot?

Yes, I can but I am not getting this exception continuously.
> What’s your event throughout?

the hostname of all client's servers.
> Events per second and bytes per second? 

getting events per 5 seconds from every machines.
> Have you tried setting up Prometheus monitoring?

No
> Is that memory usage high for the server it’s on? Is it growing or does it stay there.

it's normal not growing it stay there.

____________________________________________________________________________
I have restarted this service 3 days ago and working fine. till now I got only one below exception.
![2020-04-01_13-07](https://user-images.githubusercontent.com/26060662/78111449-4becc000-741a-11ea-9ecd-cac6b846d551.png)


Next time I will debug more things.
Thanks again.

**Comment by Jc2k** [comment] 2020-04-01 08:11
I strongly suggest running `tcpdump` and capturing to a file. Then you can use wireshark to see what was happening at the time it hung.

Also strace when its hung:

 * No output at all - process stuck in userland
 * Single partial line of output - process stuck in kernel (blocking I/O of some kind)
 * Many lines of output - process is still functional on some level and processing events

One thing that stands out is that whilst i have higher volume systems I dont think mine reconnect every time they send a message. Might be woth keeping an eye on open file descriptors to make sure old connections are getting torn down correctly. Long term if sending a message once every five seconds i'd consider moving to long lived connections.

As i've said before, **normally** `socket.send() raised an exception` is not a useful diagnostic because it happens normally with asyncio and there is no way to turn it off. Whats interesting here is that there are so many of them in close proximity. Usually its that a socket was closed by the remote end and it happens once and then not again. But I wonder if we are leaking sockets here. If you turn on the prometheus monitoring endpoint you can grab the stats with:

```
curl http://127.0.0.1:9431/metrics
```

(You need to put `--exporter=0.0.0.0:9431` in your CLI).

This will tell us how many senders it thinks are online, how many subscribers, etc.

**Comment by prashantvidja** [comment] 2020-04-01 08:35
ok

**Comment by prashantvidja** [comment] 2020-04-04 07:03
Hi @Jc2k,
I have started hpfeeds-broker 7 days ago and still, it is working fine. this time it works a long time.
I got some exception which I have sent on the upper comment.
I have attached data that I got from `curl http://127.0.0.1:8080/metrics`. by default, the exporter starts on 8080.
[exporter.log](https://github.com/Jc2k/hpfeeds3/files/4430876/exporter.log)

**Comment by prashantvidja** [comment] 2020-04-14 05:32
Hi @Jc2k 
The above issue came again and I have tested many things.

I am not getting any other exception then this `WARNING:asyncio:socket.send() raised exception`.
But after hung getting too many exceptions continuously. I have noticed that around hundreds of exceptions every 30 sec.
Getting too many exceptions after hung so we could say that the process is still functional on some level and processing events.

Also, I have checked tcpdump packet file using Wireshark but did not found any malicious IPs.
let me know what other things I can check using the packet files.

Also, I have tried to do `curl http://127.0.0.1:8080/metrics` but did not get any output due to process hang.

`netstat` command output was showing that ports are listening.
Thanks

**Comment by prashantvidja** [comment] 2020-04-22 05:55
@Jc2k 

I am using the hpfeeds-broker as publicly open.
So I have analyzed the packets and found out that issue happening due to some garbage packet we are received on the hpfeeds-broker port by suspicious IP(low reputation IP).
Two times this service goes hung due to GIOP(General Inter-ORB Protocol).
I think our service not able to close the connection when it receives this type of packet and goes into an infinite loop.
Please look it into it. if you can help.

Thanks

**Comment by Jc2k** [comment] 2020-04-22 07:00
Brilliant. Neither of my brokers are open. On one we have a script that reconfigures an ipset with a list of known clients. On the other there are tunnels so the Broker doesn’t even have a public ip. So this explains why my brokers seem so much more stable.

Does this mean you can now trigger it by replaying the packet you found? Are you able to provide a pcap of such a packet so I can reproduce it? Or the hex of the payload the scan is sending?

As this is happening before authentication my best guess is the packet has what looks like a valid header but it contains a massive length. And the remote disconnects before it sends all of the packet. Maybe the reading code doesn’t handle disconnects during such packets and gets stuck in a read loop.

**Comment by prashantvidja** [comment] 2020-04-22 18:35
Hi @Jc2k 

I don't know how to send same packet to the server. but I think it has done by some DDOS tools.
I have attached two pcap files with suspicious IP packets. When service went down I collected this type of packet.
Can we do any changes to stop this type of packet?
[suspicious_.zip](https://github.com/Jc2k/hpfeeds3/files/4518285/suspicious_.zip)

Thanks

**Comment by Jc2k** [comment] 2020-04-23 07:36
@prashantvidja 

So at an application level these pcaps look fairly benign. One of them has no payload at all, and the other has the server sending an OP_INFO packet, but the client never replies.

Did you see a lot of those types of packet? Hundreds? Thouands?

So if the broker is able to send its OP_INFO packet the scanner is definitely establishing a full TCP connection. But it's not going through our protocol parser until the client sends something. So not sure what could trigger an infinite loop so far. The connection path is the same as for a normal client, and when thats done we use a python asyncio Protocol object - theres no while loop reading from the socket, instead python calls our code when something is received from the network. That's part is not likely to fail as its been tested by the python community as a while for many years already.

So I am wondering if there are 2 issues:

 * The quick disconnect by scanners means that we try to send an OP_INFO but the client has already disconnected - so we see the `socket.send() raised exception` error. And you see lots of them because its a large number of scan packets. As i've send before, because of the way asyncio send error handling is written we may never be able to stop that log message, and if you are getting lots of scans the only way to quieten it will be with a firewall.
 * And maybe we aren't cleaning up failed connections properly. Theres some kind of resource leak that eventually breaks the broker.

You should be able to simulate this by running a broker locally or behind a firewall (to make sure a scan doesn't happen while you are testing) then connect and disconnect TCP sockets over and over again, and see if it breaks the broker.

**Comment by prashantvidja** [comment] 2020-04-24 12:59
Hi @Jc2k 

No, I am not getting thousands of packet. both times I got around 300-400 packets from one IP.
So I have tested locally by connect and disconnect TCP sockets over and over again but it does not break the broker.
Could we fix it like this guy fixed here?
https://github.com/aio-libs/aiohttp/issues/3122#issuecomment-567960647

Thanks

**Comment by Jc2k** [comment] 2020-08-05 09:32
I might have fixed this inadvertently? I found a case (though haven't got a reproducer) where the underlying python network library seemed to never call the `connection_lost` handler and ultimately thats why we try to write to a connection that is closed. This is now "fixed" (worked around) in the upstream broker (https://github.com/hpfeeds/hpfeeds/commit/c26b80e651fadaa6a582b1b9b31342bbf8009531).

I'm planning to archive this repo properly now that upstream is able to release on pypi, so for now i'm going to close this. But if it still happens on c26b80e651fadaa6a582b1b9b31342bbf8009531 or later, please open a ticket [upstream](https://github.com/hpfeeds/hpfeeds).

**Closed by Jc2k** 2020-08-05 09:32 UTC
